name: Build firmware artifact

on:
  push:

  workflow_dispatch:
    inputs:
      build-type:
        description: Build type
        type: choice
        options:
          - Release
          - Debug
          - MinSizeRel
          - RelWithDebInfo

env:
  BUILD_TYPE: ${{ inputs.build-type || 'Release' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v7

      - name: Build firmware
        uses: SBence/build-pico-project@master
        with:
          build-type: ${{ env.BUILD_TYPE }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          path: build/src/Pico_Game_Controller.uf2
          archive: false
