name: Create release

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v7

      - name: Build firmware
        uses: SBence/build-pico-project@master
        with:
          build-type: Release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: build/src/Pico_Game_Controller.uf2
